/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp test.xml -i hotel.h -a hotelAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "hotelAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RegistryAdaptor
 */

RegistryAdaptor::RegistryAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RegistryAdaptor::~RegistryAdaptor()
{
    // destructor
}

int RegistryAdaptor::checkIn(int num_room)
{
    // handle method call com.test.hotel.registry.checkIn
    int out0;
    QMetaObject::invokeMethod(parent(), "checkIn", Q_RETURN_ARG(int, out0), Q_ARG(int, num_room));
    return out0;
}

int RegistryAdaptor::checkOut(int num_room)
{
    // handle method call com.test.hotel.registry.checkOut
    int out0;
    QMetaObject::invokeMethod(parent(), "checkOut", Q_RETURN_ARG(int, out0), Q_ARG(int, num_room));
    return out0;
}

