/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp test.xml -i hotel.h -a hotelAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef HOTELADAPTOR_H_1280385635
#define HOTELADAPTOR_H_1280385635

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "hotel.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.test.hotel.registry
 */
class RegistryAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.test.hotel.registry")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.test.hotel.registry\">\n"
"    <method name=\"checkIn\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"num_room\"/>\n"
"    </method>\n"
"    <method name=\"checkOut\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"num_room\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    RegistryAdaptor(QObject *parent);
    virtual ~RegistryAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int checkIn(int num_room);
    int checkOut(int num_room);
Q_SIGNALS: // SIGNALS
};

#endif
